language: go
go:
 - "1.10"

script:
 - make clean
 - make deps
 - make test
 - make build

deploy:
  provider: script
  script: make release
  skip_cleanup: true
  on:
    tags: true
    branch: master
